const translations = {
    es: {
        meta_title: "KENIA LECHUGA",
        lbl_idioma: "IDIOMA",
        alt_hero_img: "Kenia Lechuga Remera Olímpica",
        lbl_edition: "REMO MEXICO",
        lbl_hero_title: "KENIA LECHUGA",
        btn_conoceme: "CONOCEME",
        btn_portafolio: "PORTAFOLIO DE IMAGENES",
        btn_poder_musica: "VIDEOS DE MI TRAYECTORIA",
        btn_contacto: "REDES SOCIALES",
        alt_video_thumb: "Kenia Video Preview",
        lbl_clic_reproducir: "CLIC PARA REPRODUCIR",
        btn_grandes_momentos: "GRANDES MOMENTOS",
        modal_grandes_momentos_title: "GRANDES MOMENTOS",
        modal_grandes_momentos_desc: "Toca una imagen para ampliarla y deslizarla",
        btn_cerrar: "Cerrar",
        btn_comparte_historia: "COMPARTE MI HISTORIA TE LO AGRADEZCO",
        lbl_producido_por: 'PRODUCIDO POR "TALENT CARD"',
        btn_contactanos_card: "CONTÁCTANOS",
        lbl_nombre_label: "Nombre:",
        val_nombre: "Kenia Lechuga Alanís",
        lbl_edad_label: "Edad:",
        val_edad: "32 años",
        lbl_nacimiento_label: "Nacimiento:",
        val_nacimiento: "24 Jul / Santiago, Nuevo León",
        lbl_nacionalidad_label: "Nacionalidad:",
        val_nacionalidad: "Mexicana",
        lbl_estatura_label: "Estatura / Peso:",
        val_estatura: "1.68 m / 57 kg",
        lbl_formacion_titulo: "Formación Deportiva",
        lbl_perfil_label: "Perfil:",
        val_perfil_text: "Atleta de Alto Rendimiento, Seleccionada Nacional de Remo.",
        lbl_desempeno_label: "Desempeño:",
        val_desempeno_text: "Fuerza, resistencia aeróbica extrema y máxima potencia en embarcaciones individuales.",
        lbl_especialidad_titulo: "Especialidad",
        lbl_disciplina_label: "Disciplina:",
        val_disciplina_text: "Remo (Modalidad Single Scull / Par de Remos Cortos).",
        lbl_tecnica_label: "Técnica:",
        val_tecnica_text: "Dominio técnico de alta precisión, control de ritmo en regatas y sincronización óptima de propulsión en agua.",
        lbl_logros_titulo: "Logros y Trayectoria",
        val_logro_1: "📌 Campeona mundial en el Campeonato Mundial de Remo en el Remo Bajo Techo (World Rowing Indoor Championships).",
        val_logro_2: "🥇 Medallista de oro en los Juegos Panamericanos (Lima 2019 y Santiago 2023).",
        val_logro_3: "🌐 Máxima referente histórica del remo mexicano con participación en múltiples ediciones de los Juegos Olímpicos (Río 2016, Tokio 2020 y París 2024).",
        contact_title: "REDES SOCIALES",
        contact_contracting: "Apoyame en mis Redes sociales",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_youtube: "YOUTUBE",
        qr_heading: "ESCANEA EL CÓDIGO QR",
        btn_share_qr: "COMPARTIR QR",
        cat2_t: "PORTAFOLIO DE IMAGENES",
cat2_c: "Trabajo cada día en mi preparación física y mental, aplicando una mentalidad de cero miedo y perfeccionando cada brazada para dejar a México en lo más alto",
cat3_t: "VIDEOS DE MI TRAYECTORIA",
cat3_c: "Mi mayor fortaleza es la resiliencia mental combinada con la disciplina absoluta en cada competencia",
lbl_mis_fortalezas: "México en el corazón",
btn_tributo_tri: "Campeona Mundial",
btn_junto_mar: "Llegando a México",
btn_con_gente: "Poniendo a México en Alto",
btn_cantando_beatles: "Orgullo Mexicano",
btn_video_historia: "ME PRESENTO",
btn_ver_detalles: "VER DETALLES",
lbl_biografia: "Biografía",
lbl_conoceme: "CONOCEME",
btn_regresar_menu: "REGRESAR AL MENÚ"
    },
    en: {
        meta_title: "KENIA LECHUGA",
        lbl_idioma: "LANGUAGE",
        alt_hero_img: "Kenia Lechuga Olympic Rower",
        lbl_edition: "ROWING MEXICO",
        lbl_hero_title: "KENIA LECHUGA",
        btn_conoceme: "ABOUT ME",
        btn_portafolio: "IMAGE PORTFOLIO",
        btn_poder_musica: "CAREER VIDEOS",
        btn_contacto: "SOCIAL MEDIA",
        alt_video_thumb: "Kenia Video Preview",
        lbl_clic_reproducir: "CLICK TO PLAY",
        btn_grandes_momentos: "GREAT MOMENTS",
        modal_grandes_momentos_title: "GREAT MOMENTS",
        modal_grandes_momentos_desc: "Tap an image to zoom and swipe",
        btn_cerrar: "Close",
        btn_comparte_historia: "SHARE MY STORY, I APPRECIATE IT",
        lbl_producido_por: 'PRODUCED BY "TALENT CARD"',
        btn_contactanos_card: "CONTACT US",
        lbl_nombre_label: "Name:",
        val_nombre: "Kenia Lechuga Alanís",
        lbl_edad_label: "Age:",
        val_edad: "32 years",
        lbl_nacimiento_label: "Birth:",
        val_nacimiento: "Jul 24 / Santiago, Nuevo León",
        lbl_nacionalidad_label: "Nationality:",
        val_nacionalidad: "Mexican",
        lbl_estatura_label: "Height / Weight:",
        val_estatura: "1.68 m / 57 kg",
        lbl_formacion_titulo: "Sports Training",
        lbl_perfil_label: "Profile:",
        val_perfil_text: "High Performance Athlete, National Rowing Team Member.",
        lbl_desempeno_label: "Performance:",
        val_desempeno_text: "Strength, extreme aerobic endurance, and maximum power in single boats.",
        lbl_especialidad_titulo: "Specialty",
        lbl_disciplina_label: "Discipline:",
        val_disciplina_text: "Rowing (Single Sculls modality).",
        lbl_tecnica_label: "Technique:",
        val_tecnica_text: "High-precision technical mastery, race rhythm control, and optimal water propulsion synchronization.",
        lbl_logros_titulo: "Achievements & Career",
        val_logro_1: "📌 World Champion at the World Rowing Indoor Championships.",
        val_logro_2: "🥇 Gold medalist at the Pan American Games (Lima 2019 and Santiago 2023).",
        val_logro_3: "🌐 Top historical reference of Mexican rowing with participation in multiple editions of the Olympic Games (Rio 2016, Tokyo 2020, and Paris 2024).",
        contact_title: "SOCIAL MEDIA",
        contact_contracting: "Support me on my social media",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_youtube: "YOUTUBE",
        qr_heading: "SCAN THE QR CODE",
        btn_share_qr: "SHARE QR",
        cat2_t: "IMAGE PORTFOLIO",
cat2_c: "I work every day on my physical and mental preparation, applying a zero-fear mindset and perfecting every stroke to put Mexico at the very top",
cat3_t: "CAREER VIDEOS",
cat3_c: "My greatest strength is mental resilience combined with absolute discipline in every competition",
lbl_mis_fortalezas: "Mexico in the Heart",
btn_tributo_tri: "World Champion",
btn_junto_mar: "Arriving in Mexico",
btn_con_gente: "Putting Mexico High",
btn_cantando_beatles: "Mexican Pride",
btn_video_historia: "INTRODUCING MYSELF",
btn_ver_detalles: "VIEW DETAILS",
lbl_biografia: "Biography",
lbl_conoceme: "ABOUT ME",
btn_regresar_menu: "BACK TO MENU"
    },
    pt: {
        meta_title: "KENIA LECHUGA",
        lbl_idioma: "IDIOMA",
        alt_hero_img: "Kenia Lechuga Remadora Olímpica",
        lbl_edition: "REMO MÉXICO",
        lbl_hero_title: "KENIA LECHUGA",
        btn_conoceme: "CONHEÇA-ME",
        btn_portafolio: "PORTFÓLIO DE IMAGENS",
        btn_poder_musica: "VÍDEOS DA MINHA TRAJETÓRIA",
        btn_contacto: "REDES SOCIAIS",
        alt_video_thumb: "Kenia Video Preview",
        lbl_clic_reproducir: "CLIQUE PARA REPRODUZIR",
        btn_grandes_momentos: "GRANDES MOMENTOS",
        modal_grandes_momentos_title: "GRANDES MOMENTOS",
        modal_grandes_momentos_desc: "Toque em uma imagem para ampliar e deslizar",
        btn_cerrar: "Fechar",
        btn_comparte_historia: "COMPARTILHE MINHA HISTÓRIA, EU AGRADEÇO",
        lbl_producido_por: 'PRODUZIDO POR "TALENT CARD"',
        btn_contactanos_card: "CONTATE-NOS",
        lbl_nombre_label: "Nome:",
        val_nombre: "Kenia Lechuga Alanís",
        lbl_edad_label: "Idade:",
        val_edad: "32 anos",
        lbl_nacimiento_label: "Nascimento:",
        val_nacimiento: "24 Jul / Santiago, Nuevo León",
        lbl_nacionalidad_label: "Nacionalidade:",
        val_nacionalidad: "Mexicana",
        lbl_estatura_label: "Altura / Peso:",
        val_estatura: "1.68 m / 57 kg",
        lbl_formacion_titulo: "Formação Esportiva",
        lbl_perfil_label: "Perfil:",
        val_perfil_text: "Atleta de Alto Rendimento, Selecionada Nacional de Remo.",
        lbl_desempeno_label: "Desempenho:",
        val_desempeno_text: "Força, resistência aeróbica extrema e máxima potência em barcos individuais.",
        lbl_especialidad_titulo: "Especialidade",
        lbl_disciplina_label: "Disciplina:",
        val_disciplina_text: "Remo (Modalidade Single Scull / Skiff Simples).",
        lbl_tecnica_label: "Técnica:",
        val_tecnica_text: "Domínio técnico de alta precisão, controle de ritmo em regatas e sincronização ideal de propulsão na água.",
        lbl_logros_titulo: "Conquistas e Trajetória",
        val_logro_1: "📌 Campeã mundial no Campeonato Mundial de Remo Indoor (World Rowing Indoor Championships).",
        val_logro_2: "🥇 Medalhista de ouro nos Jogos Pan-Americanos (Lima 2019 e Santiago 2023).",
        val_logro_3: "🌐 Maior referência histórica do remo mexicano com participação em múltiplas edições dos Jogos Olímpicos (Rio 2016, Tóquio 2020 e Paris 2024).",
        contact_title: "REDES SOCIAIS",
        contact_contracting: "Apoie-me nas minhas redes sociais",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_youtube: "YOUTUBE",
        qr_heading: "ESCANEIE O CÓDIGO QR",
        btn_share_qr: "COMPARTILHAR QR",
        cat2_t: "PORTFÓLIO DE IMAGENS",
cat2_c: "Trabalho todos os dias na minha preparação física e mental, aplicando uma mentalidade de zero medo e aperfeiçoando cada remada para colocar o México no topo",
cat3_t: "VÍDEOS DA MINHA TRAJETÓRIA",
cat3_c: "Minha maior força é a resiliência mental combinada com a disciplina absoluta em cada competição",
lbl_mis_fortalezas: "México no Coração",
btn_tributo_tri: "Campeã Mundial",
btn_junto_mar: "Chegando ao México",
btn_con_gente: "Elevando o México",
btn_cantando_beatles: "Orgulho Mexicano",
btn_video_historia: "ME APRESENTO",
btn_ver_detalles: "VER DETALHES",
lbl_biografia: "Biografia",
lbl_conoceme: "CONHEÇA-ME",
btn_regresar_menu: "VOLTAR AO MENU"
    },
    fr: {
        meta_title: "KENIA LECHUGA",
        lbl_idioma: "LANGUE",
        alt_hero_img: "Kenia Lechuga Rameuse Olympique",
        lbl_edition: "AVIRON MEXIQUE",
        lbl_hero_title: "KENIA LECHUGA",
        btn_conoceme: "À PROPOS DE MOI",
        btn_portafolio: "PORTEFEUILLE D'IMAGES",
        btn_poder_musica: "VIDÉOS DE MA CARRIÈRE",
        btn_contacto: "RÉSEAUX SOCIAUX",
        alt_video_thumb: "Kenia Video Preview",
        lbl_clic_reproducir: "CLIQUEZ POUR LIRE",
        btn_grandes_momentos: "GRANDS MOMENTS",
        modal_grandes_momentos_title: "GRANDS MOMENTS",
        modal_grandes_momentos_desc: "Touchez une image pour zoomer et faire glisser",
        btn_cerrar: "Fermer",
        btn_comparte_historia: "PARTEZ MON HISTOIRE, JE VOUS REMERCIE",
        lbl_producido_por: 'PRODUIT PAR "TALENT CARD"',
        btn_contactanos_card: "CONTACTEZ-NOUS",
        lbl_nombre_label: "Nom :",
        val_nombre: "Kenia Lechuga Alanís",
        lbl_edad_label: "Âge :",
        val_edad: "32 ans",
        lbl_nacimiento_label: "Naissance :",
        val_nacimiento: "24 Juil / Santiago, Nuevo León",
        lbl_nacionalidad_label: "Nationalité :",
        val_nacionalidad: "Mexicaine",
        lbl_estatura_label: "Taille / Poids :",
        val_estatura: "1.68 m / 57 kg",
        lbl_formacion_titulo: "Formation Sportive",
        lbl_perfil_label: "Profil :",
        val_perfil_text: "Athlète de Haut Niveau, Membre de l'Équipe Nationale d'Aviron.",
        lbl_desempeno_label: "Performance :",
        val_desempeno_text: "Force, endurance aérobique extrême et puissance maximale en bateaux individuels.",
        lbl_especialidad_titulo: "Spécialité",
        lbl_disciplina_label: "Discipline :",
        val_disciplina_text: "Aviron (Modalité Skiff / Single Scull).",
        lbl_tecnica_label: "Technique :",
        val_tecnica_text: "Maîtrise technique de haute précision, contrôle du rythme en course et synchronisation optimale de la propulsion dans l'eau.",
        lbl_logros_titulo: "Réalisations et Carrière",
        val_logro_1: "📌 Championne du monde aux Championnats du monde d'aviron en salle (World Rowing Indoor Championships).",
        val_logro_2: "🥇 Médaillée d'or aux Jeux panaméricains (Lima 2019 et Santiago 2023).",
        val_logro_3: "🌐 Référence historique majeure de l'aviron mexicain avec des participations à plusieurs éditions des Jeux olympiques (Rio 2016, Tokyo 2020 et Paris 2024).",
        contact_title: "RÉSEAUX SOCIAUX",
        contact_contracting: "Soutenez-moi sur mes réseaux sociaux",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_youtube: "YOUTUBE",
        qr_heading: "SCANNEZ LE CODE QR",
        btn_share_qr: "PARTAGER LE QR",
        cat2_t: "PORTEFEUILLE D'IMAGES",
cat2_c: "Je travaille chaque jour sur ma préparation physique et mentale, en appliquant un état d'esprit sans peur et en perfectionnant chaque coup de rame pour hisser le Mexique au sommet",
cat3_t: "VIDÉOS DE MA CARRIÈRE",
cat3_c: "Ma plus grande force est la résilience mentale combinée à une discipline absolue dans chaque compétition",
lbl_mis_fortalezas: "Le Mexique dans le Cœur",
btn_tributo_tri: "Championne du Monde",
btn_junto_mar: "Arrivée au Mexique",
btn_con_gente: "Faire Briller le Mexique",
btn_cantando_beatles: "Fierté Mexicaine",
btn_video_historia: "JE ME PRÉSENTE",
btn_ver_detalles: "VOIR LES DÉTAILS",
lbl_biografia: "Biographie",
lbl_conoceme: "À PROPOS DE MOI",
btn_regresar_menu: "RETOURNER AU MENU"
    },
    ko: {
        meta_title: "KENIA LECHUGA",
        lbl_idioma: "언어",
        alt_hero_img: "케니아 레추가 올림픽 조정 선수",
        lbl_edition: "조정 멕시코",
        lbl_hero_title: "KENIA LECHUGA",
        btn_conoceme: "소개",
        btn_portafolio: "이미지 포트폴리오",
        btn_poder_musica: "커리어 비디오",
        btn_contacto: "소셜 미디어",
        alt_video_thumb: "Kenia Video Preview",
        lbl_clic_reproducir: "클릭하여 재생",
        btn_grandes_momentos: "위대한 순간들",
        modal_grandes_momentos_title: "위대한 순간들",
        modal_grandes_momentos_desc: "이미지를 터치하여 확대하고 넘겨보세요",
        btn_cerrar: "닫기",
        btn_comparte_historia: "제 이야기를 공유해 주세요, 감사합니다",
        lbl_producido_por: '"TALENT CARD" 제작',
        btn_contactanos_card: "문의하기",
        lbl_nombre_label: "이름:",
        val_nombre: "Kenia Lechuga Alanís",
        lbl_edad_label: "나이:",
        val_edad: "32세",
        lbl_nacimiento_label: "생년월일:",
        val_nacimiento: "7월 24일 / 산티아고, 누에보레온",
        lbl_nacionalidad_label: "국적:",
        val_nacionalidad: "멕시코인",
        lbl_estatura_label: "신장 / 체중:",
        val_estatura: "1.68 m / 57 kg",
        lbl_formacion_titulo: "스포츠 경력 및 훈련",
        lbl_perfil_label: "프로필:",
        val_perfil_text: "고성능 선수, 멕시코 조정 국가대표.",
        lbl_desempeno_label: "퍼포먼스:",
        val_desempeno_text: "근력, 극한의 유산소 지구력, 싱글 보트에서의 최대 파워.",
        lbl_especialidad_titulo: "전문 분야",
        lbl_disciplina_label: "종목:",
        val_disciplina_text: "조정 (싱글 스컬 종목).",
        lbl_tecnica_label: "기술:",
        val_tecnica_text: "고정밀 기술 숙련도, 레이스 페이스 조절, 수중 추진력 최적화 동기화.",
        lbl_logros_titulo: "주요 성과 및 경력",
        val_logro_1: "📌 실내 조정 세계 선수권 대회(World Rowing Indoor Championships) 세계 챔피언.",
        val_logro_2: "🥇 팬아메리칸 게임 금메달리스트 (2019 리마, 2023 산티아고).",
        val_logro_3: "🌐 올림픽(2016 리우, 2020 도쿄, 2024 파리) 다수 출전 경력을 가진 멕시코 조정의 위대한 역사적 인물.",
        contact_title: "소셜 미디어",
        contact_contracting: "소셜 미디어에서 저를 응원해 주세요",
        btn_facebook: "페이스북",
        btn_instagram: "인스타그램",
        btn_youtube: "유튜브",
        qr_heading: "QR 코드 스캔",
        btn_share_qr: "QR 공유",
        cat2_t: "이미지 포트폴리오",
cat2_c: "두려움 없는 마음가짐으로 매일 신체적, 정신적 준비에 임하며, 멕시코를 최고 정점에 올려놓기 위해 모든 스트로크를 완벽하게 가꿉니다",
cat3_t: "커리어 비디오",
cat3_c: "저의 가장 큰 강점은 모든 경기에서 발휘되는 절대적인 규율과 결합된 정신적 회복력입니다",
lbl_mis_fortalezas: "마음속의 멕시코",
btn_tributo_tri: "세계 챔피언",
btn_junto_mar: "멕시코 도착",
btn_con_gente: "멕시코를 높이 빛내다",
btn_cantando_beatles: "멕시코의 자부심",
btn_video_historia: "나를 소개합니다",
btn_ver_detalles: "상세 보기",
lbl_biografia: "전기",
lbl_conoceme: "나에 대해",
btn_regresar_menu: "메뉴로 돌아가기"
    },
    de: {
        meta_title: "KENIA LECHUGA",
        lbl_idioma: "SPRACHE",
        alt_hero_img: "Kenia Lechuga Olympische Ruderin",
        lbl_edition: "RUDERN MEXIKO",
        lbl_hero_title: "KENIA LECHUGA",
        btn_conoceme: "ÜBER MICH",
        btn_portafolio: "BILDER-PORTFOLIO",
        btn_poder_musica: "KARRIEREVIDEOS",
        btn_contacto: "SOZIALE MEDIEN",
        alt_video_thumb: "Kenia Video Preview",
        lbl_clic_reproducir: "KLICKEN ZUM ABSPIELEN",
        btn_grandes_momentos: "GROSSE MOMENTE",
        modal_grandes_momentos_title: "GROSSE MOMENTE",
        modal_grandes_momentos_desc: "Tippen Sie auf ein Bild, um es zu zoomen und zu wischen",
        btn_cerrar: "Schließen",
        btn_comparte_historia: "TEILE MEINE GESCHICHTE, ICH DANKE DIR",
        lbl_producido_por: 'PRODUZIERT VON "TALENT CARD"',
        btn_contactanos_card: "KONTAKTIERE UNS",
        lbl_nombre_label: "Name:",
        val_nombre: "Kenia Lechuga Alanís",
        lbl_edad_label: "Alter:",
        val_edad: "32 Jahre",
        lbl_nacimiento_label: "Geburtstag:",
        val_nacimiento: "24. Jul / Santiago, Nuevo León",
        lbl_nacionalidad_label: "Nationalität:",
        val_nacionalidad: "Mexikanisch",
        lbl_estatura_label: "Größe / Gewicht:",
        val_estatura: "1.68 m / 57 kg",
        lbl_formacion_titulo: "Sportliches Training",
        lbl_perfil_label: "Profil:",
        val_perfil_text: "Hochleistungsathletin, Mitglied der nationalen Rudernationalmannschaft.",
        lbl_desempeno_label: "Leistung:",
        val_desempeno_text: "Kraft, extreme aerobe Ausdauer und maximale Leistung in Einer-Booten.",
        lbl_especialidad_titulo: "Spezialität",
        lbl_disciplina_label: "Disziplin:",
        val_disciplina_text: "Rudern (Einer-Boot / Single Scull).",
        lbl_tecnica_label: "Technik:",
        val_tecnica_text: "Präzisions-Technikbeherrschung, Rhythmuskontrolle bei Regatten und optimale Synchronisation des Vortriebs im Wasser.",
        lbl_logros_titulo: "Erfolge und Karriere",
        val_logro_1: "📌 Weltmeisterin bei den World Rowing Indoor Championships (Ergometer-Rudern).",
        val_logro_2: "🥇 Goldmedaillengewinnerin bei den Panamerikanischen Spielen (Lima 2019 und Santiago 2023).",
        val_logro_3: "🌐 Führende historische Persönlichkeit des mexikanischen Rudersports mit Teilnahmen an mehreren Olympischen Spielen (Rio 2016, Tokio 2020 und Paris 2024).",
        contact_title: "SOZIALE MEDIEN",
        contact_contracting: "Unterstütze mich in meinen sozialen Medien",
        btn_facebook: "FACEBOOK",
        btn_instagram: "INSTAGRAM",
        btn_youtube: "YOUTUBE",
        qr_heading: "QR-CODE SCANNEN",
        btn_share_qr: "QR TEILEN",
        cat2_t: "BILDER-PORTFOLIO",
cat2_c: "Ich arbeite jeden Tag an meiner physischen und mentalen Vorbereitung, wende eine angstfreie Mentalität an und perfekten jeden Schlag, um Mexiko ganz nach oben zu bringen",
cat3_t: "KARRIEREVIDEOS",
cat3_c: "Meine größte Stärke ist die mentale Belastbarkeit kombiniert mit absoluter Disziplin in jedem Wettkampf",
lbl_mis_fortalezas: "Mexiko im Herzen",
btn_tributo_tri: "Weltmeisterin",
btn_junto_mar: "Ankunft in Mexiko",
btn_con_gente: "Mexiko ganz nach oben bringen",
btn_cantando_beatles: "Mexikanischer Stolz",
btn_video_historia: "ICH STELLE MICH VOR",
btn_ver_detalles: "DETAILS ANZEIGEN",
lbl_biografia: "Biografie",
lbl_conoceme: "ÜBER MICH",
btn_regresar_menu: "ZURÜCK ZUM MENÜ"
    },
    ja: {
        meta_title: "KENIA LECHUGA",
        lbl_idioma: "言語",
        alt_hero_img: "ケニア・レチュガ オリンピックボート選手",
        lbl_edition: "ローイング メキシコ",
        lbl_hero_title: "KENIA LECHUGA",
        btn_conoceme: "私について",
        btn_portafolio: "画像ポートフォリオ",
        btn_poder_musica: "キャリアビデオ",
        btn_contacto: "ソーシャルメディア",
        alt_video_thumb: "Kenia Video Preview",
        lbl_clic_reproducir: "クリックして再生",
        btn_grandes_momentos: "大いなる瞬間",
        modal_grandes_momentos_title: "大いなる瞬間",
        modal_grandes_momentos_desc: "画像をタップして拡大・スワイプします",
        btn_cerrar: "閉じる",
        btn_comparte_historia: "私のストーリーをシェアしてください、ありがとうございます",
        lbl_producido_por: '制作: "TALENT CARD"',
        btn_contactanos_card: "お問い合わせ",
        lbl_nombre_label: "氏名:",
        val_nombre: "Kenia Lechuga Alanís",
        lbl_edad_label: "年齢:",
        val_edad: "32歳",
        lbl_nacimiento_label: "生年月日:",
        val_nacimiento: "7月24日 / サンティアゴ、ヌエボ・レオン",
        lbl_nacionalidad_label: "国籍:",
        val_nacionalidad: "メキシコ",
        lbl_estatura_label: "身長 / 体重:",
        val_estatura: "1.68 m / 57 kg",
        lbl_formacion_titulo: "スポーツ経歴",
        lbl_perfil_label: "プロフィール:",
        val_perfil_text: "ハイパフォーマンスアスリート、ローイング（ボート競技）メキシコ代表選手。",
        lbl_desempeno_label: "パフォーマンス:",
        val_desempeno_text: "筋力、極限の有酸素持久力、シングルボートでの最大パワー。",
        lbl_especialidad_titulo: "専門種目",
        lbl_disciplina_label: "種目:",
        val_disciplina_text: "ローイング（シングルスカル種目）。",
        lbl_tecnica_label: "技術:",
        val_tecnica_text: "高精度な技術的習熟、レガッタでのリズム制御、水中での最適な推進力同期。",
        lbl_logros_titulo: "実績とキャリア",
        val_logro_1: "📌 ワールドローイング・インドア・チャンピオンシップ（室内ローイング世界選手権）世界王者。",
        val_logro_2: "🥇 パンアメリカン競技大会（2019年リマ、2023年サンティアゴ）金メダリスト。",
        val_logro_3: "🌐 オリンピック（2016年リオ、2020年東京、2024年パリ）に複数回出場し、メキシコローイング界の歴史的な第一人者として活躍。",
        contact_title: "ソーシャルメディア",
        contact_contracting: "SNSで私を応援してください",
        btn_facebook: "フェイスブック",
        btn_instagram: "インスタグラム",
        btn_youtube: "ユーチューブ",
        qr_heading: "QRコードをスキャン",
        btn_share_qr: "QRをシェア",
        cat2_t: "画像ポートフォリオ",
cat2_c: "恐怖心のないメンタリティを持ち、毎日心身のトレーニングに励み、メキシコを最高峰に導くためにすべてのストロークを磨き上げています",
cat3_t: "キャリアビデオ",
cat3_c: "私の最大の強さは、あらゆる競技における絶対的な規律と結びついた精神的な回復力です",
lbl_mis_fortalezas: "心にメキシコを",
btn_tributo_tri: "世界王者",
btn_junto_mar: "メキシコ到着",
btn_con_gente: "メキシコを高みへ",
btn_cantando_beatles: "メキシコの誇り",
btn_video_historia: "自己紹介",
btn_ver_detalles: "詳細を見る",
lbl_biografia: "伝記",
lbl_conoceme: "私について",
btn_regresar_menu: "メニューに戻る"
    },
    zh: {
        meta_title: "KENIA LECHUGA",
        lbl_idioma: "语言",
        alt_hero_img: "克尼亚·莱丘加 奥运赛艇运动员",
        lbl_edition: "赛艇 墨西哥",
        lbl_hero_title: "KENIA LECHUGA",
        btn_conoceme: "关于我",
        btn_portafolio: "图片作品集",
        btn_poder_musica: "生涯视频",
        btn_contacto: "社交媒体",
        alt_video_thumb: "Kenia Video Preview",
        lbl_clic_reproducir: "点击播放",
        btn_grandes_momentos: "精彩时刻",
        modal_grandes_momentos_title: "精彩时刻",
        modal_grandes_momentos_desc: "点击图片放大并滑动查看",
        btn_cerrar: "关闭",
        btn_comparte_historia: "分享我的故事，非常感谢",
        lbl_producido_por: '由 "TALENT CARD" 制作',
        btn_contactanos_card: "联系我们",
        lbl_nombre_label: "姓名：",
        val_nombre: "Kenia Lechuga Alanís",
        lbl_edad_label: "年龄：",
        val_edad: "32 岁",
        lbl_nacimiento_label: "出生日期：",
        val_nacimiento: "7月24日 / 新莱昂州圣地亚哥",
        lbl_nacionalidad_label: "国籍：",
        val_nacionalidad: "墨西哥",
        lbl_estatura_label: "身高 / 体重：",
        val_estatura: "1.68 m / 57 kg",
        lbl_formacion_titulo: "运动背景",
        lbl_perfil_label: "个人简介：",
        val_perfil_text: "高水平运动员，墨西哥国家赛艇队队员。",
        lbl_desempeno_label: "表现：",
        val_desempeno_text: "力量、极致有氧耐力以及单人艇上的最大推进功率。",
        lbl_especialidad_titulo: "专长项目",
        lbl_disciplina_label: "项目：",
        val_disciplina_text: "赛艇（单人双桨项目 Single Scull）。",
        lbl_tecnica_label: "技术：",
        val_tecnica_text: "高精度技术掌握、赛场节奏控制以及水中推进力的最佳同步。",
        lbl_logros_titulo: "成就与生涯",
        val_logro_1: "📌 世界室内赛艇锦标赛（World Rowing Indoor Championships）世界冠军。",
        val_logro_2: "🥇 泛美运动会（2019年利马和2023年圣地亚哥）金牌得主。",
        val_logro_3: "🌐 墨西哥赛艇史上的最高标杆，曾多次参加奥运会（2016年里约、2020年东京和2024年巴黎）。",
        contact_title: "社交媒体",
        contact_contracting: "在社交媒体上支持我",
        btn_facebook: "脸书",
        btn_instagram: "照片墙",
        btn_youtube: "油管",
        qr_heading: "扫描二维码",
        btn_share_qr: "分享二维码",
        cat2_t: "图片作品集",
cat2_c: "我每天都在进行身体和心理上的准备，秉持零恐惧的心态，完美每一个划桨动作，将墨西哥带到最高峰",
cat3_t: "生涯视频",
cat3_c: "我最大的优势是将心理韧性与每场比赛中的绝对纪律相结合",
lbl_mis_fortalezas: "墨西哥在心中",
btn_tributo_tri: "世界冠军",
btn_junto_mar: "抵达墨西哥",
btn_con_gente: "让墨西哥大放异彩",
btn_cantando_beatles: "墨西哥的骄傲",
btn_video_historia: "自我介绍",
btn_ver_detalles: "查看详情",
lbl_biografia: "传记",
lbl_conoceme: "关于我",
btn_regresar_menu: "返回菜单"
    }
};

function changeLanguage(lang) {
    localStorage.setItem('selectedLanguage', lang);

    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    const altElements = document.querySelectorAll('[data-i18n-alt]');
    altElements.forEach(el => {
        const key = el.getAttribute('data-i18n-alt');
        if (translations[lang] && translations[lang][key]) {
            el.setAttribute('alt', translations[lang][key]);
        }
    });

    if (translations[lang] && translations[lang]['meta_title']) {
        document.title = translations[lang]['meta_title'];
    }

    document.querySelectorAll('.lang-chip').forEach(chip => {
        chip.classList.remove('active');
        if (chip.getAttribute('onclick').includes(`'${lang}'`)) {
            chip.classList.add('active');
        }
    });
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('selectedLanguage') || 'es';
    changeLanguage(savedLang);
});